"""Update LeadSource enum

Revision ID: f87bbebe4fb6
Revises: 875d4264eef0
Create Date: 2026-08-12 17:46:07.966459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87bbebe4fb6'
down_revision: Union[str, None] = '875d4264eef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute("ALTER TYPE leadsource ADD VALUE IF NOT EXISTS 'linkedin_anamika'")
        op.execute("ALTER TYPE leadsource ADD VALUE IF NOT EXISTS 'linkedin_yati'")
        op.execute("ALTER TYPE leadsource ADD VALUE IF NOT EXISTS 'linkedin_nidhi'")
        op.execute("ALTER TYPE leadsource ADD VALUE IF NOT EXISTS 'linkedin_disha'")
        op.execute("ALTER TYPE leadsource ADD VALUE IF NOT EXISTS 'linkedin_parmeeta'")
    elif bind.engine.name != 'sqlite':
        with op.batch_alter_table('leads', schema=None) as batch_op:
            batch_op.alter_column('source',
                   existing_type=sa.VARCHAR(length=13),
                   type_=sa.Enum('linkedin', 'linkedin_anamika', 'linkedin_yati', 'linkedin_nidhi', 'linkedin_disha', 'linkedin_parmeeta', 'website', 'referral', 'cold_email', 'cold_whatsapp', 'instagram', 'event', 'other', name='leadsource'),
                   existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.engine.name != 'sqlite' and bind.engine.name != 'postgresql':
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('leads', schema=None) as batch_op:
            batch_op.alter_column('source',
                   existing_type=sa.Enum('linkedin', 'linkedin_anamika', 'linkedin_yati', 'linkedin_nidhi', 'linkedin_disha', 'linkedin_parmeeta', 'website', 'referral', 'cold_email', 'cold_whatsapp', 'instagram', 'event', 'other', name='leadsource'),
                   type_=sa.VARCHAR(length=13),
                   existing_nullable=True)
        # ### end Alembic commands ###
